### PR TITLE
Add emails to tdx tickets

### PR DESCRIPTION
**Pull request by britaumich**
- Set up the application's time zone to Eastern Time (US & Canada)
- Add a select list of email addresses where to send TDX tickets.
- create app preferences for TDX tickets destination emails
- add app preferences and buildings nicknames to seeds file
- rename 'no_access_reason_pref' preference to 'no_access_reason'

After pulling the branch run `bin/rails db:seed` command

### CODE REVIEW

**Review by palinaskakun — DISMISSED** [review]
All looks good. I tested for all types of emails, I can see a different email for Dana building and SKB building, and I can also see the nicknames now. Code looks good!

**Comment by charlieezh** [comment]
all codes looking good, tdx tickets are sent to different emails for the building selected, except that they are in a format like "Email seas-facilities@umich.edu" in which the "Email " could be deleted later

**Comment by britaumich** [comment]
@charlieezh Thank you for noticing extra words in the custom facility emails. I missed that when I copied them into the seeds file from the email with the list of all TDX ticket destination emails.
Could you please do the following to test that changes I pushed are correct:

- delete App Preferences for TDX emails (here http://localhost:3000/app_preferences)
- run `bin/rails db:seed` command
- test TDX tickets for DANA and SKB buildings

Thank you

**Comment by charlieezh** [comment]
it is working all fine now. just need to delete the original ones in the preference first before running db:seed again

**Pull request merged**
